 configs:
   params:
     server.insecure: true
 server:
   ingress:
     enabled: true
     annotations:
       nginx.ingress.kubernetes.io/backend-protocol: HTTP
     hosts:
       - "argocd.127.0.0.1.nip.io"